# Generated by Django 3.0.8 on 2021-07-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_response', models.IntegerField(default=0, verbose_name='Response from users')),
                ('searched_query', models.CharField(max_length=500, verbose_name='Query from the user')),
                ('first', models.CharField(max_length=500, verbose_name='Highest recommendation')),
                ('second', models.CharField(max_length=500, verbose_name='Second Highest recommendation')),
                ('third', models.CharField(max_length=500, verbose_name='Third Highest recommendation')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendation',
                'db_table': 'recommendation',
            },
        ),
    ]
