# Generated by Django 3.0.8 on 2021-07-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='first',
            field=models.CharField(max_length=500, null=True, verbose_name='Highest recommendation'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='searched_query',
            field=models.CharField(max_length=500, null=True, verbose_name='Query from the user'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='second',
            field=models.CharField(max_length=500, null=True, verbose_name='Second Highest recommendation'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='third',
            field=models.CharField(max_length=500, null=True, verbose_name='Third Highest recommendation'),
        ),
    ]
