# Generated by Django 3.0.8 on 2021-07-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20210728_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='first_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='second_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='third_score',
            field=models.FloatField(null=True),
        ),
    ]
