# Generated by Django 3.0.8 on 2021-07-28 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20210728_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='users_response',
            new_name='user_response',
        ),
    ]
