# Generated by Django 3.0.8 on 2021-07-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_auto_20210728_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='user_response',
            field=models.IntegerField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Response from users'),
        ),
    ]
